# Generated by Django 4.1.3 on 2022-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='broker_image',
            field=models.ImageField(upload_to='broker_pic'),
        ),
    ]
