# Generated by Django 4.1.3 on 2022-11-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_alter_contact_broker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image1',
            field=models.ImageField(default='default.jpg', upload_to='listing_pic'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image2',
            field=models.ImageField(default='default.jpg', upload_to='listing_pic'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image3',
            field=models.ImageField(default='default.jpg', upload_to='listing_pic'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image4',
            field=models.ImageField(default='default.jpg', upload_to='listing_pic'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_image5',
            field=models.ImageField(default='default.jpg', upload_to='listing_pic'),
        ),
    ]
