# Generated by Django 4.1.3 on 2022-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_listing_listing_image1_listing_listing_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image1',
            field=models.ImageField(upload_to='listing_pic'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image2',
            field=models.ImageField(upload_to='listing_pic'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image3',
            field=models.ImageField(upload_to='listing_pic'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image4',
            field=models.ImageField(upload_to='listing_pic'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_image5',
            field=models.ImageField(upload_to='listing_pic'),
        ),
    ]
