# Generated by Django 4.1.3 on 2022-11-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_alter_listing_listing_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_description',
            field=models.TextField(max_length=300),
        ),
    ]
